# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YrZjWKkEMw1Sqk4NMG08GrzTFTitfL5a
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import os

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

from sklearn.preprocessing import label_binarize

# --------------------------------------------------------
# PAGE CONFIGURATION
# --------------------------------------------------------

st.set_page_config(
    page_title="Dry Bean Classification",
    page_icon="🌱",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --------------------------------------------------------
# CUSTOM CSS
# --------------------------------------------------------

st.markdown("""
<style>
    .metric-card {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 20px;
        border-radius: 12px;
        color: white;
        text-align: center;
        margin: 5px;
    }
    .metric-card h2 { font-size: 2rem; margin: 0; }
    .metric-card p  { font-size: 0.9rem; margin: 0; opacity: 0.85; }

    .prediction-box {
        background: linear-gradient(135deg, #11998e, #38ef7d);
        padding: 25px;
        border-radius: 14px;
        color: white;
        text-align: center;
        font-size: 1.5rem;
        font-weight: bold;
        margin: 15px 0;
    }
    .section-header {
        border-left: 5px solid #667eea;
        padding-left: 12px;
        margin: 20px 0 10px 0;
        font-size: 1.2rem;
        font-weight: 600;
    }
</style>
""", unsafe_allow_html=True)

# --------------------------------------------------------
# SIDEBAR
# --------------------------------------------------------

st.sidebar.image(
    "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/BITS_Pilani-Logo.svg/200px-BITS_Pilani-Logo.svg.png",
    width=160
)

st.sidebar.title("🌱 Dry Bean Classifier")
st.sidebar.caption("AIMLCZG565 – Machine Learning | Assignment 2")

st.sidebar.divider()

page = st.sidebar.radio(
    "Navigate",
    [
        "🏠 Home",
        "📊 Dataset Explorer",
        "🤖 Single Prediction",
        "📁 Batch Prediction",
        "📈 Model Comparison",
        "🌳 Feature Importance",
        "ℹ️ About"
    ]
)

st.sidebar.divider()

# --------------------------------------------------------
# LOAD DATASET & MODELS
# --------------------------------------------------------

@st.cache_data
def load_dataset():
    # Corrected URL for the raw Excel file on GitHub
    return pd.read_excel("https://raw.githubusercontent.com/mansijain56-oss/dry-bean-classification/main/Dry_Bean_Dataset.xlsx", engine='openpyxl')

@st.cache_resource
def load_models():
    MODEL_DIR = "model"
    return {
        "Logistic Regression": joblib.load(os.path.join(MODEL_DIR, "logistic_regression.pkl")),
        "Decision Tree":       joblib.load(os.path.join(MODEL_DIR, "decision_tree.pkl")),
        "KNN":                 joblib.load(os.path.join(MODEL_DIR, "knn.pkl")),
        "Naive Bayes":         joblib.load(os.path.join(MODEL_DIR, "naive_bayes.pkl")),
        "Random Forest":       joblib.load(os.path.join(MODEL_DIR, "random_forest.pkl"))
    }, \
    joblib.load(os.path.join(MODEL_DIR, "scaler.pkl")), \
    joblib.load(os.path.join(MODEL_DIR, "label_encoder.pkl"))

df = load_dataset()
models, scaler, encoder = load_models()

# --------------------------------------------------------
# SIDEBAR STATS
# --------------------------------------------------------

st.sidebar.markdown("**Dataset Stats**")
st.sidebar.markdown(f"- Records: **{df.shape[0]:,}**")
st.sidebar.markdown(f"- Features: **{df.shape[1]-1}**")
st.sidebar.markdown(f"- Classes: **{df['Class'].nunique()}**")
st.sidebar.markdown(f"- Models: **{len(models)}**")

# --------------------------------------------------------
# FEATURE NAMES
# --------------------------------------------------------

FEATURES = [
    "Area", "Perimeter", "MajorAxisLength", "MinorAxisLength",
    "AspectRation", "Eccentricity", "ConvexArea", "EquivDiameter",
    "Extent", "Solidity", "roundness", "Compactness",
    "ShapeFactor1", "ShapeFactor2", "ShapeFactor3", "ShapeFactor4"
]

TARGET = "Class"

# --------------------------------------------------------
# EVALUATION FUNCTION
# --------------------------------------------------------

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    metrics = {
        "Accuracy":  accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, average="weighted"),
        "Recall":    recall_score(y_test, y_pred, average="weighted"),
        "F1 Score":  f1_score(y_test, y_pred, average="weighted"),
        "MCC":       matthews_corrcoef(y_test, y_pred),
    }
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)
        y_bin  = label_binarize(y_test, classes=np.unique(y_test))
        metrics["ROC-AUC"] = roc_auc_score(y_bin, y_prob, multi_class="ovr", average="weighted")
    else:
        metrics["ROC-AUC"] = np.nan
    return metrics

# ==========================================================
# HOME PAGE
# ==========================================================

if page == "🏠 Home":

    st.title("🌱 Dry Bean Classification System")
    st.markdown("##### BITS Pilani WILP · AIMLCZG565 Machine Learning · Assignment 2")
    st.divider()

    c1, c2, c3, c4 = st.columns(4)
    c1.markdown('<div class="metric-card"><h2>13,611</h2><p>Records</p></div>', unsafe_allow_html=True)
    c2.markdown('<div class="metric-card"><h2>16</h2><p>Features</p></div>', unsafe_allow_html=True)
    c3.markdown('<div class="metric-card"><h2>7</h2><p>Bean Classes</p></div>', unsafe_allow_html=True)
    c4.markdown('<div class="metric-card"><h2>5</h2><p>ML Models</p></div>', unsafe_allow_html=True)

    st.divider()

    col1, col2 = st.columns(2)

    with col1:
        st.markdown('<div class="section-header">🎯 Objectives</div>', unsafe_allow_html=True)
        st.markdown("""
        - Explore and analyze the Dry Bean Dataset
        - Train and evaluate five ML classifiers
        - Compare model performance across six metrics
        - Deploy an interactive prediction interface
        """)

        st.markdown('<div class="section-header">🤖 Models Used</div>', unsafe_allow_html=True)
        for m in models:
            st.markdown(f"- {m}")

    with col2:
        st.markdown('<div class="section-header">📊 Class Distribution</div>', unsafe_allow_html=True)
        fig, ax = plt.subplots(figsize=(6, 4))
        counts = df["Class"].value_counts()
        colors = sns.color_palette("viridis", len(counts))
        ax.barh(counts.index, counts.values, color=colors)
        ax.set_xlabel("Count")
        ax.invert_yaxis()
        plt.tight_layout()
        st.pyplot(fig)

    st.divider()
    try:
        comparison = pd.read_csv("output/model_comparison.csv")
        best_model = comparison.loc[
            comparison["Accuracy"].idxmax(),
            "Model"
        ]

        best_accuracy = comparison["Accuracy"].max()

        st.success(
            f"🏆 {best_model} achieved the highest accuracy "
            f"({best_accuracy:.4f}) among all models."
        )

    except Exception:
        st.success("🏆 Model comparison results are available in the Model Comparison page.")

# ==========================================================
# DATASET EXPLORER
# ==========================================================

elif page == "📊 Dataset Explorer":

    st.title("📊 Dataset Explorer")
    st.divider()

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Rows",     df.shape[0])
    c2.metric("Columns",  df.shape[1])
    c3.metric("Features", df.shape[1] - 1)
    c4.metric("Classes",  df["Class"].nunique())

    st.divider()

    tab1, tab2, tab3, tab4, tab5 = st.tabs([
            "📋 Preview", "📈 Distribution", "🔥 Correlation", "📉 Histograms", "📝 Feature Info"
        ])

    with tab1:
            st.dataframe(df.head(10), use_container_width=True)
            st.divider()
            st.markdown("**Summary Statistics**")
            st.dataframe(df.describe().T.style.background_gradient(cmap="Blues"), use_container_width=True)

    with tab2:
            fig, ax = plt.subplots(figsize=(9, 5))
            sns.countplot(
                data=df, x="Class",
                order=df["Class"].value_counts().index,
                palette="viridis", ax=ax
            )
            ax.set_title("Bean Class Distribution")
            plt.xticks(rotation=30)
            for p in ax.patches:
                ax.annotate(f'{int(p.get_height())}',
                            (p.get_x() + p.get_width() / 2., p.get_height()),
                            ha='center', va='bottom', fontsize=9)
            plt.tight_layout()
            st.pyplot(fig)

    with tab3:
            fig2, ax2 = plt.subplots(figsize=(12, 8))
            sns.heatmap(
                df.drop("Class", axis=1).corr(),
                cmap="coolwarm", annot=False,
                linewidths=0.5, ax=ax2
            )
            ax2.set_title("Feature Correlation Heatmap")
            plt.tight_layout()
            st.pyplot(fig2)

    with tab4:
            selected_feature = st.selectbox("Select Feature", FEATURES)
            fig3, ax3 = plt.subplots(figsize=(9, 4))
            for cls in df["Class"].unique():
                subset = df[df["Class"] == cls][selected_feature]
                ax3.hist(subset, bins=30, alpha=0.5, label=cls)
            ax3.set_xlabel(selected_feature)
            ax3.set_ylabel("Frequency")
            ax3.set_title(f"Distribution of {selected_feature} by Class")
            ax3.legend(fontsize=7)
            plt.tight_layout()
            st.pyplot(fig3)

    with tab5:
            feature_info = pd.DataFrame({
                "Feature": FEATURES,
                "Min":    [round(df[f].min(), 4) for f in FEATURES],
                "Max":    [round(df[f].max(), 4) for f in FEATURES],
                "Mean":   [round(df[f].mean(), 4) for f in FEATURES],
                "Median": [round(df[f].median(), 4) for f in FEATURES],
            })
            st.dataframe(feature_info, use_container_width=True)

# ==========================================================
# SINGLE PREDICTION
# ==========================================================

elif page == "🤖 Single Prediction":

    st.title("🤖 Single Bean Prediction")
    st.markdown("Enter feature values to predict the bean variety.")
    st.divider()

    with st.expander("⚙️ Input Features", expanded=True):
        input_data = []
        col1, col2 = st.columns(2)
        for i, feature in enumerate(FEATURES):
            with (col1 if i % 2 == 0 else col2):
                value = st.number_input(
                    feature,
                    value=float(df[feature].median()),
                    format="%.4f"
                )
            input_data.append(value)

    selected_model = st.selectbox("🤖 Select Model", list(models.keys()))

    if st.button("🔍 Predict Bean Class", use_container_width=True):

        input_df = pd.DataFrame([input_data], columns=FEATURES)
        scaled   = scaler.transform(input_df)
        pred     = models[selected_model].predict(scaled)[0]
        bean     = encoder.inverse_transform([pred])[0]

        st.markdown(
            f'<div class="prediction-box">🌱 Predicted Bean: {bean}</div>',
            unsafe_allow_html=True
        )

        if hasattr(models[selected_model], "predict_proba"):

            probability = models[selected_model].predict_proba(scaled)[0]
            top_conf    = probability.max() * 100

            st.metric("Top Confidence", f"{top_conf:.1f}%")

            prob_df = pd.DataFrame({
                "Bean Variety": encoder.classes_,
                "Probability":  probability
            }).sort_values("Probability", ascending=False)

            col1, col2 = st.columns(2)

            with col1:
                st.markdown("**Prediction Probabilities**")
                st.dataframe(
                    prob_df.style.format({"Probability": "{:.2%}"})
                           .background_gradient(subset=["Probability"], cmap="Greens"),
                    use_container_width=True
                )

            with col2:
                fig, ax = plt.subplots(figsize=(6, 4))
                colors = ["#38ef7d" if v == bean else "#667eea" for v in prob_df["Bean Variety"]]
                ax.barh(prob_df["Bean Variety"], prob_df["Probability"], color=colors)
                ax.set_xlabel("Probability")
                ax.set_title("Confidence per Class")
                ax.invert_yaxis()
                plt.tight_layout()
                st.pyplot(fig)

# ==========================================================
# BATCH PREDICTION
# ==========================================================

elif page == "📁 Batch Prediction":

    st.title("📁 Batch Prediction")
    st.markdown("Upload a CSV with the 16 feature columns to predict all records at once.")
    st.divider()

    col1, col2 = st.columns([2, 1])

    with col1:
        uploaded = st.file_uploader("Upload CSV File", type=["csv"])

    with col2:
        selected_model = st.selectbox("Select Model", list(models.keys()))

    if uploaded is not None:

        batch = pd.read_csv(uploaded)

        st.markdown("**Uploaded Data Preview**")
        st.dataframe(batch.head(), use_container_width=True)

        if st.button("▶ Run Batch Prediction", use_container_width=True):

            missing = [c for c in FEATURES if c not in batch.columns]

            if missing:
                st.error(f"Missing columns: {missing}")
            else:
                scaled     = scaler.transform(batch[FEATURES])
                prediction = encoder.inverse_transform(models[selected_model].predict(scaled))
                batch["Predicted_Class"] = prediction

                st.success(f"✅ Prediction complete — {len(batch)} records processed.")

                # Summary
                st.markdown("**Prediction Summary**")
                summary = batch["Predicted_Class"].value_counts().reset_index()
                summary.columns = ["Bean Variety", "Count"]

                col1, col2 = st.columns(2)
                with col1:
                    st.dataframe(summary, use_container_width=True)
                with col2:
                    fig, ax = plt.subplots(figsize=(5, 4))
                    ax.pie(
                        summary["Count"],
                        labels=summary["Bean Variety"],
                        autopct="%1.1f%%",
                        colors=sns.color_palette("viridis", len(summary))
                    )
                    ax.set_title("Predicted Class Distribution")
                    plt.tight_layout()
                    st.pyplot(fig)

                st.dataframe(batch, use_container_width=True)

                st.download_button(
                    "⬇ Download Results",
                    data=batch.to_csv(index=False).encode("utf-8"),
                    file_name="DryBean_Predictions.csv",
                    mime="text/csv",
                    use_container_width=True
                )

# ==========================================================
# MODEL COMPARISON
# ==========================================================

elif page == "📈 Model Comparison":

    st.title("📈 Model Performance Comparison")
    st.divider()

    try:
        comparison = pd.read_csv("output/model_comparison.csv")

        metrics = ["Accuracy", "Precision", "Recall", "F1 Score", "MCC", "ROC-AUC"]

        # Top model cards
        best = comparison.loc[comparison["Accuracy"].idxmax()]
        c1, c2, c3 = st.columns(3)
        c1.metric("🏆 Best Model",    best["Model"])
        c2.metric("🎯 Best Accuracy", f"{best['Accuracy']:.4f}")
        c3.metric("📊 Best F1 Score", f"{best['F1 Score']:.4f}")

        st.divider()

        tab1, tab2, tab3, tab4 = st.tabs(["📋 Metrics Table", "📊 Bar Chart", "🕸 Radar Chart", "🔲 Confusion Matrix"])

        with tab1:
            st.dataframe(
                comparison.style
                    .background_gradient(subset=metrics, cmap="Greens")
                    .format({m: "{:.4f}" for m in metrics}),
                use_container_width=True
            )

        with tab2:
            fig, ax = plt.subplots(figsize=(12, 5))
            comparison.set_index("Model")[metrics].plot(kind="bar", ax=ax, colormap="viridis")
            ax.set_ylabel("Score")
            ax.set_ylim(0.85, 1.0)
            ax.legend(loc="lower right", fontsize=8)
            plt.xticks(rotation=20)
            plt.tight_layout()
            st.pyplot(fig)

        with tab3:
            radar_metrics = ["Accuracy", "Precision", "Recall", "F1 Score", "MCC"]
            N = len(radar_metrics)
            angles = [n / float(N) * 2 * np.pi for n in range(N)]
            angles += angles[:1]

            fig, ax = plt.subplots(figsize=(7, 7), subplot_kw=dict(polar=True))
            colors = sns.color_palette("viridis", len(comparison))

            for i, row in comparison.iterrows():
                values = [row[m] for m in radar_metrics]
                values += values[:1]
                ax.plot(angles, values, color=colors[i], linewidth=2, label=row["Model"])
                ax.fill(angles, values, color=colors[i], alpha=0.1)

            ax.set_xticks(angles[:-1])
            ax.set_xticklabels(radar_metrics, fontsize=10)
            ax.set_ylim(0.85, 1.0)
            ax.legend(loc="upper right", bbox_to_anchor=(1.3, 1.1), fontsize=9)
            ax.set_title("Model Radar Comparison", pad=20)
            plt.tight_layout()
            st.pyplot(fig)

        with tab4:
            st.markdown("**Confusion Matrix per Model**")
            selected_cm_model = st.selectbox("Select Model for Confusion Matrix", list(models.keys()), key="cm_model")

            # Load the held-out test dataset
            test_data = pd.read_csv("output/test_data.csv")

            X_test = test_data[FEATURES]
            y_test = test_data[TARGET].astype(int)

            y_pred = models[selected_cm_model].predict(X_test)

            cm = confusion_matrix(y_test, y_pred)

            fig_cm, ax_cm = plt.subplots(figsize=(8, 6))
            sns.heatmap(
                cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=encoder.classes_,
                yticklabels=encoder.classes_,
                ax=ax_cm
            )
            ax_cm.set_xlabel("Predicted")
            ax_cm.set_ylabel("Actual")
            ax_cm.set_title(f"Confusion Matrix - {selected_cm_model}")
            plt.tight_layout()
            st.pyplot(fig_cm)

            # Classification Report
            st.markdown("**Classification Report**")
            report = classification_report(y_test,y_pred,target_names=encoder.classes_,output_dict=True)
            report_df = pd.DataFrame(report).transpose()
            st.dataframe(
                report_df.style.format("{:.4f}").background_gradient(cmap="Greens"),
                use_container_width=True
            )

    except Exception as e:
        st.error(f"Error loading model comparison: {e}")

# ==========================================================
# FEATURE IMPORTANCE
# ==========================================================

elif page == "🌳 Feature Importance":

    st.title("🌳 Feature Importance")
    st.divider()

    rf = models["Random Forest"]

    importance = pd.DataFrame({
        "Feature":    FEATURES,
        "Importance": rf.feature_importances_
    }).sort_values("Importance", ascending=False).reset_index(drop=True)

    importance["Rank"] = range(1, len(importance) + 1)

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("**Feature Importance Scores**")
        st.dataframe(
            importance[["Rank", "Feature", "Importance"]]
            .style.format({"Importance": "{:.4f}"})
                  .background_gradient(subset=["Importance"], cmap="Greens"),
            use_container_width=True
        )

    with col2:
        fig, ax = plt.subplots(figsize=(7, 6))
        colors = sns.color_palette("viridis", len(importance))
        ax.barh(importance["Feature"], importance["Importance"], color=colors)
        ax.set_xlabel("Importance Score")
        ax.set_title("Random Forest Feature Importance")
        ax.invert_yaxis()
        plt.tight_layout()
        st.pyplot(fig)

    st.divider()

    # Cumulative importance
    importance["Cumulative"] = importance["Importance"].cumsum()
    fig2, ax2 = plt.subplots(figsize=(10, 4))
    ax2.plot(importance["Feature"], importance["Cumulative"], marker="o", color="#667eea")
    ax2.axhline(y=0.8, color="red", linestyle="--", label="80% threshold")
    ax2.set_ylabel("Cumulative Importance")
    ax2.set_title("Cumulative Feature Importance")
    ax2.legend()
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    st.pyplot(fig2)

    top3 = importance["Feature"].head(3).tolist()
    st.info(f"Top 3 most important features: **{', '.join(top3)}**")

# ==========================================================
# ABOUT PAGE
# ==========================================================

elif page == "ℹ️ About":

    st.title("ℹ️ About This Project")
    st.divider()

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("""
### 🌱 Dry Bean Classification

Developed as part of **BITS Pilani WILP – AIMLCZG565 Machine Learning Assignment 2**.

**Dataset:** Dry Bean Dataset (UCI ML Repository)
- 13,611 records · 16 features · 7 classes

**Models:** Logistic Regression, Decision Tree, KNN, Naive Bayes, Random Forest

**Metrics:** Accuracy, Precision, Recall, F1, MCC, ROC-AUC
        """)

    with col2:
        st.markdown("""
### 👩‍🎓 Student Details

| Field | Details |
|---|---|
| Name | Mansi Jain |
| ID | 2025AC05151 |
| Course | AIMLCZG565 |
| Programme | M.Tech AI & ML |
| University | BITS Pilani WILP |
        """)

    st.divider()

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Dataset Records", "13,611")
    c2.metric("ML Models", "5")
    c3.metric("Classes", "7")
    c4.metric("Features", "16")

    st.success("✔ Developed using Python · Streamlit · Scikit-learn")

# ==========================================================
# FOOTER
# ==========================================================

st.divider()
st.markdown("""
<center>
<small>
<b>BITS Pilani Work Integrated Learning Programme</b> &nbsp;|&nbsp;
AIMLCZG565 – Machine Learning &nbsp;|&nbsp;
Assignment 2 &nbsp;|&nbsp;
Dry Bean Classification &nbsp;|&nbsp;
© 2026 Mansi Jain
</small>
</center>
""", unsafe_allow_html=True)